### PR TITLE
Fix wrong parameter in call for write_to_file

### LINKED ISSUE #16: `--write_to_file` doesn't work

### PR DESCRIPTION
**Pull request by brendon-boldt**
A function was being called with the wrong argument.

Close #16

### CODE REVIEW

**Review by FelixLabelle — COMMENTED** [review]
It looks good, but why did you switch from os to pathlib? 

I'm going to approve it either way, but the change seems a little unnecessary. Especially considering the issue was 1 line (line 92).

**Comment by brendon-boldt** [comment]
I added type annotations and my software developer side took over :man_shrugging:

**Comment by FelixLabelle** [comment]
> 
> 
> I added type annotations and my software developer side took over 🤷‍♂

Is there an advantage or is it because it makes typing easier?

**Comment by brendon-boldt** [comment]
I think `pathlib` is cleaner.

**Review by FelixLabelle — APPROVED** [review]

**Pull request merged**
